"""CSV-backed vector store using embeddings generated by local Ollama."""

from __future__ import annotations

import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path

from config import (
    OLLAMA_EMBEDDING_MODEL,
    VECTOR_SOURCE_CSV,
    VECTOR_STORE_CSV,
    VECTOR_TOP_K,
)
from ollama_client import embed_text


@dataclass(frozen=True)
class SearchResult:
    source_id: str
    title: str
    content: str
    source: str
    score: float


def _cosine_similarity(left: list[float], right: list[float]) -> float:
    if len(left) != len(right) or not left:
        return 0.0

    dot = sum(a * b for a, b in zip(left, right))
    left_norm = math.sqrt(sum(value * value for value in left))
    right_norm = math.sqrt(sum(value * value for value in right))
    if left_norm == 0 or right_norm == 0:
        return 0.0
    return dot / (left_norm * right_norm)


def _read_source_rows(source_path: Path) -> list[dict[str, str]]:
    if not source_path.exists():
        raise FileNotFoundError(f"Knowledge source CSV was not found: {source_path}")

    with source_path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {"id", "title", "content", "source"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Knowledge source CSV is missing columns: {', '.join(sorted(missing))}")

        rows = []
        for row in reader:
            content = (row.get("content") or "").strip()
            if not content:
                continue
            rows.append(
                {
                    "id": (row.get("id") or "").strip(),
                    "title": (row.get("title") or "").strip(),
                    "content": content,
                    "source": (row.get("source") or "").strip(),
                }
            )
    return rows


def build_vector_store(
    source_path: Path = VECTOR_SOURCE_CSV,
    store_path: Path = VECTOR_STORE_CSV,
) -> int:
    """Create the generated CSV vector store from the safe source knowledge CSV."""
    rows = _read_source_rows(source_path)
    store_path.parent.mkdir(parents=True, exist_ok=True)

    with store_path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=["id", "title", "content", "source", "embedding_model", "embedding"],
        )
        writer.writeheader()
        for row in rows:
            embedding = embed_text(f"{row['title']}\n{row['content']}")
            writer.writerow(
                {
                    **row,
                    "embedding_model": OLLAMA_EMBEDDING_MODEL,
                    "embedding": json.dumps(embedding, separators=(",", ":")),
                }
            )

    return len(rows)


def _store_needs_rebuild(source_path: Path, store_path: Path) -> bool:
    if not store_path.exists():
        return True
    if source_path.stat().st_mtime > store_path.stat().st_mtime:
        return True

    try:
        with store_path.open("r", encoding="utf-8", newline="") as handle:
            first = next(csv.DictReader(handle), None)
        return first is None or first.get("embedding_model") != OLLAMA_EMBEDDING_MODEL
    except (OSError, csv.Error):
        return True


def ensure_vector_store() -> None:
    if _store_needs_rebuild(VECTOR_SOURCE_CSV, VECTOR_STORE_CSV):
        build_vector_store()


def search(query: str, top_k: int = VECTOR_TOP_K) -> list[SearchResult]:
    ensure_vector_store()
    query_embedding = embed_text(query)
    matches: list[SearchResult] = []

    with VECTOR_STORE_CSV.open("r", encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            try:
                embedding = [float(value) for value in json.loads(row.get("embedding") or "[]")]
            except (TypeError, ValueError, json.JSONDecodeError):
                continue

            matches.append(
                SearchResult(
                    source_id=row.get("id", ""),
                    title=row.get("title", ""),
                    content=row.get("content", ""),
                    source=row.get("source", ""),
                    score=_cosine_similarity(query_embedding, embedding),
                )
            )

    matches.sort(key=lambda item: item.score, reverse=True)
    return matches[: max(1, top_k)]


def retrieve_guidance(query: str, top_k: int = VECTOR_TOP_K) -> str:
    results = search(query, top_k=top_k)
    if not results:
        return "No local guidance entries were retrieved."

    sections = []
    for result in results:
        sections.append(
            f"- {result.title}: {result.content} "
            f"(source: {result.source or 'local project guidance'})"
        )
    return "\n".join(sections)
